### PR TITLE
fix(q2): Xonotic with gametype CA

### LINKED ISSUE #89: Xonotic servers with CA gametype with >0 players, returns error
**Conditions:**
At least 1 player(s) playing
Gametype is CA
Qstat version: 2.15

**Following errors out:**
```
$ qstat -R -json -xonotics 136.243.145.236:30142
[
	{
		"protocol": "xonotics",
		"address": "136.243.145.236:30142",
		"status": "error",
		"hostname": "136.243.145.236:30142",
		"error": ".297794 49 2 \"Kano\""
	}
]
```

**This one works:**

```
$ qstat -json -xonotics 136.243.145.236:30142
[
	{
		"protocol": "xonotics",
		"address": "136.243.145.236:30142",
		"status": "online",
		"hostname": "136.243.145.236:30142",
		"name": "[WTWRP] Votable (2)",
		"gametype": "Xonotic",
		"map": "bloodrun_a3",
		"numplayers": 12,
		"maxplayers": 24,
		"numspectators": 0,
		"maxspectators": 0,
		"ping": 20,
		"retries": 0
	}
]
```

**Reported by:**
martin-t ramses nmc tommy @ xonotic discord/irc

### PR DESCRIPTION
**Pull request by stevenh**
Fix q2 parsing for Xonotic with gametype CA which has a leading float for damage not int for frags.

Fixes #89

### CODE REVIEW

File: qstat.c [hunk 1]
```diff
@@ -6521,7 +6521,22 @@ player_info:            debug(3, "player info");
...
+			rc = sscanf(pkt, "%d.%d %n", &frags, &ping, &len);
+			ping = 0; // Just a temp variable so reset.
+			if (rc == 2) {
+				// Xonotic in CA mode shows damage (float) instead of frags (int)
+				// 1.0 == 100 dmg.
+				float frags_f;
+
+				if ((rc = sscanf(pkt, "%f %n", &frags_f, &len)) == 1) {
+					frags = (int)(frags_f*100);
+				}
```
Comment (darkliquid) [inline qstat.c:6534]: could you simply _not_ reset ping and instead skip the second `sscanf` by doing `frags = (frags * 100) + ping` (assuming ping is always going to be at most 2 decimal places, if it isn't, you could use a while loop to do an integer divide by ten to truncate it until the value was =< 99 and then add it, though at that point it's probably more complicated than a second `sscanf`)

File: qstat.c [hunk 2]
```diff
@@ -6521,7 +6521,22 @@ player_info:            debug(3, "player info");
 				break;
 			}
 
-			rc = sscanf(pkt, "%d %n", &frags, &len);
+			// Detect if we have a leading float or int?
+			rc = sscanf(pkt, "%d.%d %n", &frags, &ping, &len);
+			ping = 0; // Just a temp variable so reset.
+			if (rc == 2) {
```
Comment (darkliquid) [inline qstat.c:6527]: Isn't there a danger here that `rc==2` means that `ping` and `len` was set but not `frags`? I guess they should all be init to 0 anyway, so probably not a big deal, but also if all 3 are scanned, meaning `rc==3`, then you wont enter the case where you are actually parsing the float value, some explanation here as to why this is okay (if indeed it is) wouldn't go amiss in the comments here.

Comment (stevenh) [reply qstat.c:6527]: rc explicitly doesn't include `%n` assignments.

> Nothing is expected; instead, the number of characters consumed thus far from the input is  stored  through               the next pointer, which must be a pointer to int.  This is not a conversion and does not increase the count               returned by the function.

File: qstat.c (hunk 1 above)
Comment (stevenh) [reply qstat.c:6534]: The decimals aren't limited to two, so as you say this is still the clearest way to do this.

Comment (lwaddicor) [reply qstat.c:6534]: There is also that it may be that the decimal part of the number could not be loaded into a int, and in this case i believe sscanf would set ping to -1. So +1 to reloading with sscanf into a float

**Review by lwaddicor — APPROVED** [review]
Looks good to me

File: qstat.c (hunk 2 above)
Comment (darkliquid) [reply qstat.c:6527]: ahh, thanks for clearing that up, i missed that in the docs.

**Review by darkliquid — APPROVED** [review]
